name: Build and Push DPO Telegram Bot
run-name: Bot Deployment triggered by ${{ github.actor }}

on:
  workflow_dispatch:  # This makes the workflow manual

jobs:
  build:
    runs-on: [self-hosted, custom-vm-1]
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} custom server"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
